engineering/urls.py
from django.urls import path
from . import views

app_name = 'engineering'
urlpatterns = [
        path('deshboard/', views.deshboard, name='deshboard'),
        path('deshboard/<int:exam_id>/', views.detail, name='detail'),
        path('deshboard/fom/', views.post_new, name='fom'),
        path('ajax/load-semester/', views.load_semester, name='ajax_load_semester'),
        path('ajax/load-subject/', views.load_subject, name='ajax_load_subject'),

]

helm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('engineering/', include('engineering.urls')),

    # all auth
    path('accounts/', include('allauth.urls')),  # new

    # default auth modify
    path('users/', include('users.urls')),  # new

    #  smart select
    path('chaining/', include('smart_selects.urls')),  # new

    # default auth with django
    # path('users/', include('django.contrib.auth.urls')), # new
]


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns += [
    path('sentry-debug/', trigger_error),
    # ...
]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

engineering/forms.py
from django import forms

from .models import EngineeringExamApplication, \
                    EngineeringExamApplicationSubject, \
                    EngineeringSubject, \
                    EngineeringExam, \
                    EngineeringExamApplicationSubjectUser

from django.forms import modelformset_factory
from django.forms import formset_factory, inlineformset_factory


class ExamForm(forms.ModelForm):
    class Meta:
        model = EngineeringExamApplication
        fields = ('exam', 'exam_type',)


class SubjectForm(forms.ModelForm):
    class Meta:
        model = EngineeringExamApplicationSubjectUser
        fields = ('stream', 'semester', 'subject',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['semester'] = forms.ChoiceField()
        self.fields['subject'] = forms.ChoiceField()


SubjectFormset = inlineformset_factory(
                        EngineeringExamApplication,
                        EngineeringExamApplicationSubjectUser,
                        form=SubjectForm,
                        extra=5,
                )


# SubjectFormSet = formset_factory(SubjectForm, extra=2)


# -----------------------------------------------------------------------
# model form with specific field
# class ExamForm(forms.ModelForm):
#     class Meta:
#         model = EngineeringExamApplication
#         fields = ('exam', 'exam_type',)


# model form with metod and customize model field
# and update data
# class ExamForm(forms.ModelForm):
#     class Meta:
#         model = EngineeringExamApplication
#         fields = ('exam', 'exam_type',)

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         EXAM_CHOICES = (
#             ('R', 'Reguler'),
#             ('K', 'KT'),
#         )
#         self.fields['exam_type'] = forms.ChoiceField(
#                                                     label=('exam'),
#                                                     choices=EXAM_CHOICES
#                                                 )
#         data = EngineeringExam.objects.all()
#         self.fields['exam'] = forms.ChoiceField(
#             label=('exxam'),
#             choices=[('------', '------')] + [(d.id, d.name) for d in data],
#             widget=forms.Select(attrs={'class': 'span12'})
#         )


# normal form with init method and data bind
# class ExamForm(forms.Form):
#     exam_type = forms.ChoiceField()
#     exam = forms.ChoiceField()

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)

#         EXAM_CHOICES = (
#             ('R', 'Reguler'),
#             ('K', 'KT'),
#         )

#         self.fields['exam_type'] = forms.ChoiceField(
#                                                     label=('exam'),
#                                                     choices=EXAM_CHOICES
#                                                 )

#         data = EngineeringExam.objects.all()
#         self.fields['exam'] = forms.ChoiceField(
#             label=('exxam'),
#             choices=[(d.id, d.name) for d in data],
#             widget=forms.Select(attrs={'class': 'span12'})
#         )

engineering/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import EngineeringOutcome, EngineeringExam
from .models import EngineeringSemester, EngineeringSubject, EngineeringExamApplication, EngineeringExamApplicationSubject, EngineeringExamApplicationSubjectUser
from .forms import ExamForm, SubjectFormset
from django.shortcuts import redirect

# Create your views here.
@login_required
def deshboard(request):

    qs = EngineeringOutcome.objects.filter(user=request.user).order_by('-exam')
    d = []
    for x in qs:
        d.append(x.exam)

    q = EngineeringExam.objects.filter(name__in=d)

    if request.method == 'GET':
        examfom = ExamForm(request.GET or None)
        formset = SubjectFormset(request.GET or None)
    elif request.method == 'POST':
        examfom = ExamForm(request.POST)
        formset = SubjectFormset(request.POST)
        if examfom.is_valid() and formset.is_valid():
            # first save this book, as its reference will be used in `Author`

            examfom = examfom.save(commit=False)
            examfom.user = request.user  # The logged-in user
            examfom.save()

            for form in formset:

                form = form.save(commit=False)
                form.form = examfom  # The logged-in user
                form.save()
                obj, created = EngineeringExamApplicationSubject.objects.get_or_create(form=examfom, stream=form.stream, semester=form.semester, subject=form.subject)
                obj.save()
                # print(form.cleaned_data['stream'])
                # print(form.cleaned_data['semester'])
                # print(form.cleaned_data['subject'])
            return redirect('engineering:deshboard')

    context = {
        'result': qs,
        'exam': q,
        'form': examfom,
        'formset': formset,
    }
    return render(request, 'engineering/deshboard.html', context)


def detail(request, exam_id):

    all_result = EngineeringOutcome.objects.filter(user=request.user).\
                    order_by('-exam')
    exams = []
    for x in all_result:
        exams.append(x.exam)

    exa = EngineeringExam.objects.filter(name__in=exams)

    if exam_id:
        all_result = []
        all_result = EngineeringOutcome.objects.filter(
                                    user=request.user,
                                    exam=exam_id).order_by('-exam')

    if request.method == 'GET':
        examfom = ExamForm(request.GET or None)
        formset = SubjectFormset(request.GET or None)
    elif request.method == 'POST':
        examfom = ExamForm(request.POST)
        formset = SubjectFormset(request.POST)
        if examfom.is_valid() and formset.is_valid():
            # first save this book, as its reference will be used in `Author`

            examfom = examfom.save(commit=False)
            examfom.user = request.user  # The logged-in user
            examfom.save()

            for form in formset:

                form = form.save(commit=False)
                form.form = examfom  # The logged-in user
                form.save()
                obj, created = EngineeringExamApplicationSubject.objects.get_or_create(form=examfom, stream=form.stream, semester=form.semester, subject=form.subject)
                obj.save()
                # print(form.cleaned_data['stream'])
                # print(form.cleaned_data['semester'])
                # print(form.cleaned_data['subject'])
            return redirect('engineering:deshboard')

    context = {
        'result': all_result,
        'exam': exa,
        'form': examfom,
        'formset': formset,
    }

    return render(request, 'engineering/deshboard.html', context)


# def post_new(request):
#     form = ExamForm()
#     return render(request, 'engineering/fom.html', {'form': form})

def load_semester(request):
    stream_id = request.GET.get('stream')
    semester = EngineeringSemester.objects.filter(stream_id=stream_id)
    print(semester)
    return render(request, 'hr/semester_list_options.html', {'semester': semester})


def load_subject(request):
    stream_id = request.GET.get('stream')
    semester_id = request.GET.get('semester')
    print(semester_id)
    print(stream_id)
    subject = EngineeringSubject.objects.filter(stream_id=stream_id, semester_id=semester_id)
    print(subject)
    return render(request, 'hr/subject_list_options.html', {'subject': subject})


def post_new(request):
    template_name = 'engineering/fom.html'
    if request.method == 'GET':
        examfom = ExamForm(request.GET or None)
        formset = SubjectFormset(request.GET or None)
    elif request.method == 'POST':
        examfom = ExamForm(request.POST)
        formset = SubjectFormset(request.POST)
        if examfom.is_valid() and formset.is_valid():
            # first save this book, as its reference will be used in `Author`

            examfom = examfom.save(commit=False)
            examfom.user = request.user  # The logged-in user
            examfom.save()

            for form in formset:

                form = form.save(commit=False)
                form.form = examfom  # The logged-in user
                form.save()
                obj, created = EngineeringExamApplicationSubject.objects.get_or_create(form=examfom, stream=form.stream, semester=form.semester, subject=form.subject)
                obj.save()
                # print(form.cleaned_data['stream'])
                # print(form.cleaned_data['semester'])
                # print(form.cleaned_data['subject'])
            return redirect('engineering:deshboard')
    return render(request, template_name, {
        'form': examfom,
        'formset': formset,
    })




# def create_book_with_authors(request):
#     template_name = 'engineering/fom.html'
#     username = "not logged in"
   
#     if request.method == "POST":
#         #Get the posted form
#         MyLoginForm = LoginForm(request.POST)
      
#         if MyLoginForm.is_valid():
#             username = MyLoginForm.cleaned_data['username']
#     else:
#         MyLoginForm = Loginform()
		
#     return render(request, template_name, {"username" : username})

templates/engineering/deshboard.html
{% extends "base.html" %}

{% block head_title %} Deshboard {{ block.super }}{% endblock %}

{% block content %}


<div class="container-fluid">
	<div class="row main-row">
		<div class="col-12">

			<div class="outer-border">

				<div class="heading-wrapper">
					<div class="row">
						<div class="col-12 ml-auto mr-auto">
							<h2 class="recoard_head">
								Exam Recoards
							</h2>
						</div>
					</div>
				</div>


				<div class="row">
					<div class="col-2 table-responsive recoard-side-menu">
						<table class="table">
							<thead>
								{% for e in exam %}
								<tr>
									<td><a href="{% url 'engineering:detail' e.id %}">{{ e }}</a> </td>
								</tr>
								{% endfor %}
							</thead>
						</table>
					</div>
					<div class="col-10 table-responsive recoard-side-data">
						<table class="table">
							<thead>
								<tr>
									<th>Subject</th>
									<th>Ia</th>
									<th>Ia Grade</th>
									<th>Tw</th>
									<th>Tw Grade</th>
									<th>Or</th>
									<th>Oe Grade</th>
									<th>Pr</th>
									<th>Pr Grade</th>
									<th>Tr</th>
									<th>Tr Grade</th>
								</tr>
							</thead>
							<tbody>
								{% for exam in result %}

								<tr>
									<td class="subject"> {{exam.subject}} </td>
									<td> {{exam.internal_assessment}} </td>
									<td> {{exam.internal_assessment_grade}} </td>
				
									<td> {{exam.term_work}} </td>
									<td> {{exam.term_work_grade}} </td>
				
									<td> {{exam.oral}} </td>
									<td> {{exam.oral_grade}} </td>
				
									<td> {{exam.oral_and_practical}} </td>
									<td> {{exam.oral_and_practical_grade}} </td>
				
									<td> {{exam.end_sem_exam}} </td>
									<td> {{exam.end_sem_exam_grade}} </td>
				
								</tr>

								{% endfor %}

							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- 
<div class="container outer-border">

	<div class="row heading">
		<h2 class="heading-text">Exam Recoards</h2>
	</div>

	<div class="row table-row">

		<table class="table">
			<thead>
				<tr>
					<th>Exam</th>
					<th>Subject</th>
					<th>Ia</th>
					<th>Ia Grade</th>
					<th>Tw</th>
					<th>Tw Grade</th>
					<th>Or</th>
					<th>Oe Grade</th>
					<th>Pr</th>
					<th>Pr Grade</th>
					<th>Tr</th>
					<th>Tr Grade</th>
				</tr>
			</thead>
			<tbody>
				{% for exam in result %}
				<tr>
					<td> {{exam.exam}} </td>
					<td> {{exam.subject}} </td>
					<td> {{exam.internal_assessment}} </td>
					<td> {{exam.internal_assessment_grade}} </td>

					<td> {{exam.term_work}} </td>
					<td> {{exam.term_work_grade}} </td>

					<td> {{exam.oral}} </td>
					<td> {{exam.oral_grade}} </td>

					<td> {{exam.oral_and_practical}} </td>
					<td> {{exam.oral_and_practical_grade}} </td>

					<td> {{exam.end_sem_exam}} </td>
					<td> {{exam.end_sem_exam_grade}} </td>
				</tr>
				{% endfor %}
			</tbody>
		</table>

	</div>
</div> -->


{% endblock %}

templates/engineering/fom.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
        {% with page_title="Exam Form" %}
        {% include "page_title.html" %}
        {% endwith %}

    <div class="row">
    <div class="col-md-4 offset-md-4">
    {% comment %} <h2>Exam Form</h2> {% endcomment %}

    <form method="POST" class="post-form">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        {% bootstrap_form form %}

            <table class="table">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                {% comment %} <th>{{ field.label|capfirst }}</th> {% endcomment %}
                                {% bootstrap_label field.label %}
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="{% cycle row1 row2 %} formset_row">
                        {% for field in form.visible_fields %}
                            <td>
                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% comment %} {{ field }} {% endcomment %}
                                {% bootstrap_field field %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    
    </div>
    </div>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'Add Subject',
            deleteText: 'remove',
            prefix: 'engineeringexamapplicationsubjectuser_set'
        });
    </script>
    <script>
        var streamId0;
        var semesterId0;
        $("#id_engineeringexamapplicationsubjectuser_set-0-stream").change(function () {
            streamId0 = $(this).val();

            $.ajax({
                url: '/engineering/ajax/load-semester/',
                type: "GET",
                data: {
                    'stream': streamId0
                },
                success: function (data) {
                    $("#id_engineeringexamapplicationsubjectuser_set-0-semester").html(data);
                }
            });

        });

        $("#id_engineeringexamapplicationsubjectuser_set-0-semester").change(function () {
            semesterId0 = $(this).val();
            console.log(semesterId0);
            console.log(streamId0);
            $.ajax({
                url: '/engineering/ajax/load-subject/',
                type: "GET",
                data: {
                    'stream': streamId0,
                    'semester': semesterId0,

                },
                success: function (data) {
                    console.log(data);
                    $("#id_engineeringexamapplicationsubjectuser_set-0-subject").html(data);
                }
            });

        });
    </script>
    <script>
        var streamId1;
        var semesterId1;
        $("#id_engineeringexamapplicationsubjectuser_set-1-stream").change(function () {
            streamId1 = $(this).val();

            $.ajax({
                url: '/engineering/ajax/load-semester/',
                type: "GET",
                data: {
                    'stream': streamId1
                },
                success: function (data) {
                    $("#id_engineeringexamapplicationsubjectuser_set-1-semester").html(data);
                }
            });

        });

        $("#id_engineeringexamapplicationsubjectuser_set-1-semester").change(function () {
            semesterId1 = $(this).val();
            console.log(semesterId1);
            console.log(streamId1);
            $.ajax({
                url: '/engineering/ajax/load-subject/',
                type: "GET",
                data: {
                    'stream': streamId1,
                    'semester': semesterId1,

                },
                success: function (data) {
                    console.log(data);
                    $("#id_engineeringexamapplicationsubjectuser_set-1-subject").html(data);
                }
            });

        });
    </script>
    <script>
        var streamId2;
        var semesterId2;
        $("#id_engineeringexamapplicationsubjectuser_set-2-stream").change(function () {
            streamId2 = $(this).val();

            $.ajax({
                url: '/engineering/ajax/load-semester/',
                type: "GET",
                data: {
                    'stream': streamId2
                },
                success: function (data) {
                    $("#id_engineeringexamapplicationsubjectuser_set-2-semester").html(data);
                }
            });

        });

        $("#id_engineeringexamapplicationsubjectuser_set-2-semester").change(function () {
            semesterId2 = $(this).val();
            console.log(semesterId2);
            console.log(streamId2);
            $.ajax({
                url: '/engineering/ajax/load-subject/',
                type: "GET",
                data: {
                    'stream': streamId2,
                    'semester': semesterId2,

                },
                success: function (data) {
                    console.log(data);
                    $("#id_engineeringexamapplicationsubjectuser_set-2-subject").html(data);
                }
            });

        });
    </script>
    <script>
        var streamId3;
        var semesterId3;
        $("#id_engineeringexamapplicationsubjectuser_set-3-stream").change(function () {
            streamId3 = $(this).val();

            $.ajax({
                url: '/engineering/ajax/load-semester/',
                type: "GET",
                data: {
                    'stream': streamId3
                },
                success: function (data) {
                    $("#id_engineeringexamapplicationsubjectuser_set-3-semester").html(data);
                }
            });

        });

        $("#id_engineeringexamapplicationsubjectuser_set-3-semester").change(function () {
            semesterId3 = $(this).val();
            console.log(semesterId3);
            console.log(streamId3);
            $.ajax({
                url: '/engineering/ajax/load-subject/',
                type: "GET",
                data: {
                    'stream': streamId3,
                    'semester': semesterId3,

                },
                success: function (data) {
                    console.log(data);
                    $("#id_engineeringexamapplicationsubjectuser_set-3-subject").html(data);
                }
            });

        });
    </script>


    <script>
        var streamId4;
        var semesterId4;
        $("#id_engineeringexamapplicationsubjectuser_set-4-stream").change(function () {
            streamId4 = $(this).val();

            $.ajax({
                url: '/engineering/ajax/load-semester/',
                type: "GET",
                data: {
                    'stream': streamId4
                },
                success: function (data) {
                    $("#id_engineeringexamapplicationsubjectuser_set-4-semester").html(data);
                }
            });

        });

        $("#id_engineeringexamapplicationsubjectuser_set-4-semester").change(function () {
            semesterId4 = $(this).val();
            console.log(semesterId4);
            console.log(streamId4);
            $.ajax({
                url: '/engineering/ajax/load-subject/',
                type: "GET",
                data: {
                    'stream': streamId4,
                    'semester': semesterId4,

                },
                success: function (data) {
                    console.log(data);
                    $("#id_engineeringexamapplicationsubjectuser_set-4-subject").html(data);
                }
            });

        });
    </script>
{% endblock %}