engineering/urls.py
from django.urls import path
from . import views

app_name = 'engineering'
urlpatterns = [
        path('deshboard/', views.deshboard, name='deshboard'),
        path('deshboard/<int:exam_id>/', views.detail, name='detail'),
        path('deshboard/fom/', views.post_new, name='fom'),
        path('ajax/load-semester/', views.load_semester, name='ajax_load_semester'),
        path('ajax/load-subject/', views.load_subject, name='ajax_load_subject'),

]

helm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('engineering/', include('engineering.urls')),

    # all auth
    path('accounts/', include('allauth.urls')),  # new

    # default auth modify
    path('users/', include('users.urls')),  # new

    #  smart select
    path('chaining/', include('smart_selects.urls')),  # new

    # default auth with django
    # path('users/', include('django.contrib.auth.urls')), # new
]


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns += [
    path('sentry-debug/', trigger_error),
    # ...
]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/_alerts.html
{% if messages %}
{% for message in messages %}

    <div class="col">
        <div id="message" class="container">
            
            <div class=" myAlert-bottom alert alert-{{message.tags}} alert-dismissible text-center" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span></button>
                    <strong>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                            Error
                        {% else %} 
                            {{ message.tags | title }}                   
                        {% endif %}
                    </strong>
                    {{ message }}
            </div>

        </div>
    </div>
    
      
{% endfor %}
{% endif %}

templates/base.html
<!DOCTYPE html>
{% load constant %}
{% load static %}

<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>{% block head_title %}| Exam System{% endblock %}</title>

  {% block headcontent %}
  {% endblock %}

{% if debug_flag == True %}
  <!-- debug true -->
  {% load compile_static %}
  <link rel="shortcut icon" href="{% static 'favicon.ico'%}" type="image/x-icon">
  <link rel="stylesheet" href="{% static "scss/main.scss"|compile %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand:300&display=swap" rel="stylesheet">

{% else %}
  <!-- debug false -->
  <link rel="shortcut icon" href="{% static 'favicon.ico'%}" type="image/x-icon">
  <link rel="stylesheet" href="{% static "compiled_file/scss/main.css" %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand:300&display=swap" rel="stylesheet">

{% endif %}

  
  {% block headcontent_end %}{% endblock %}

</head>

<body>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script type=text/javascript>
                toastr.options = {
                  "closeButton": false,
                  "debug": false,
                  "newestOnTop": false,
                  "progressBar": true,
                  "positionClass": "toast-top-right",
                  "preventDuplicates": false,
                  "onclick": null,
                  "showDuration": "300",
                  "hideDuration": "1000",
                  "timeOut": "5000",
                  "extendedTimeOut": "1000",
                  "showEasing": "swing",
                  "hideEasing": "linear",
                  "showMethod": "fadeIn",
                  "hideMethod": "fadeOut"
                }
                toastr.{{ message.tags }}('{{ message }}'); 
                </script>
            {% elif message.tags == 'info' %}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
            {% elif message.tags == 'warning' %}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
            {% elif message.tags == 'error' %}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
            {% endif %}
        {% endfor %}
    {% endif %}


  {% include "navbar.html" %}
  {% block content %}{% endblock %}
  {% include "footer.html" %}

</body>

</html>

templates/footer.html
  <footer class="site-footer">
  <hr/>
  <div class="bottom">
    <div class="container">
      <div class="row">

        <div class="col-lg-6 col-xs-12 text-lg-left text-center">
          <p class="copyright-text">
            © J Creation
          </p>
          <div class="credits">
            Designed by <a href="#">J Kotadiya</a>
          </div>
        </div>

        <div class="col-lg-6 col-xs-12 text-lg-right text-center">
          <ul class="list-inline">
            <li class="list-inline-item">
              {% comment %} <a href="{% url 'landing' %}">Home</a> {% endcomment %}
            </li>

            <li class="list-inline-item">
              <a href="{% url 'about' %}">About Us</a>
            </li>

            <li class="list-inline-item">
              <a href="{% url 'contact' %}">Contact Us</a>
            </li>

            <li class="list-inline-item">
              <a href="{% url 'contribute' %}">contribute</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/home.html
{% extends "base.html" %}

{% block head_title %} Homepage {{ block.super }}{% endblock %}

{% block content %}
<div class="container">

  {% with page_title="Homepage" %}
  {% include "page_title.html" %}
  {% endwith %}

  <div class="row">
    <div class="col-sm-12">
      <p>Ut consequat pharetra urna vel viverra. Sed elementum mauris id nisl sagittis, quis dictum neque egestas. Nulla dapibus justo non turpis tristique laoreet quis ut ante. Donec sit amet risus aliquam, scelerisque mauris rhoncus, viverra tellus. Proin arcu ipsum, maximus accumsan iaculis vitae, vulputate in eros. Proin est odio, vulputate id nulla vel, dignissim congue mi. Ut sit amet enim ac sem consectetur porta a in odio. Donec vel consectetur velit. Morbi iaculis aliquam euismod. Duis ut mollis urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur finibus, sem at imperdiet placerat, sapien dui venenatis mi, id hendrerit justo sapien iaculis justo. Aliquam sit amet mi in libero faucibus pharetra. </p>
    </div>
  </div>
</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <a class="navbar-brand" href="/">Engineering Exam System</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'engineering:deshboard' %}">Deshboard</a>
        </li>
      {% endif %}
      {% comment %} <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li> {% endcomment %}
    </ul>
    
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Hey {{ user.username }}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          {% if user.is_staff %}
          <a class="dropdown-item" href="/admin">Admin</a>
          {% endif %}
          {% comment %} <a class="dropdown-item" href="/userprofile/{{ user.id }}/">Profile</a> {% endcomment %}
          <a class="dropdown-item" href="/accounts/logout">Log out</a>
        </div>
      {% else %}
      <li class="nav-item"><a class="nav-link" href="/accounts/login">Log in</a></li>
      <li class="nav-item"><a class="nav-link" href="/accounts/signup">Sign up</a></li>
      {% endif %}
    </ul>

  </div>

</nav>

templates/page_title.html
<div class="row mt-3">
  <div class="col text-center">
    <h3>{{ page_title }}</h3>
  </div>
</div>