helm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('engineering/', include('engineering.urls')),

    # all auth
    path('accounts/', include('allauth.urls')),  # new

    # default auth modify
    path('users/', include('users.urls')),  # new

    #  smart select
    path('chaining/', include('smart_selects.urls')),  # new

    # default auth with django
    # path('users/', include('django.contrib.auth.urls')), # new
]


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns += [
    path('sentry-debug/', trigger_error),
    # ...
]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

primary_data/models.py
from django.db import models
from django.utils.text import slugify
from smart_selects.db_fields import ChainedForeignKey


# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=200)
    iso2 = models.CharField(max_length=50, blank=True)
    iso3 = models.CharField(max_length=50, blank=True)
    phone_code = models.CharField(blank=True, max_length=100)
    capital = models.CharField(max_length=100, blank=True)
    currency = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=200)
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Citie(models.Model):
    name = models.CharField(max_length=200)
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING)
    state = ChainedForeignKey(
                            State,
                            chained_field="country",
                            chained_model_field="country",
                            null=True,
                            blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=100)
    book_slug = models.SlugField(max_length=150, unique=True)
    primary_author_first_name = models.CharField(
                                                "Author First",
                                                max_length=100,
                                                blank=True)
    primary_author_last_name = models.CharField(
                                                "Author Last",
                                                max_length=100,
                                                blank=True)
    pub_date = models.DateField("Book Pub Date", blank=True, null=True)

    def __str__(self):
        return self.name


class Subject(models.Model):
    name = models.CharField(max_length=150)
    subject_slug = models.SlugField(max_length=150, unique=True)
    code = models.CharField(max_length=250)
    book = models.ManyToManyField(Book, blank=True)

    def __str__(self):
        return self.name + " " + self.code


class Universitie(models.Model):
    name = models.CharField(max_length=200)
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING)
    domain = models.CharField(max_length=200, blank=True)
    web_page = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

templates/hr/person_form.html
{% extends 'base.html' %}

{% block content %}

  <h2>Person Form</h2>

  <form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'person_changelist' %}">Nevermind</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_country").change(function () {
      var url = $("#personForm").attr("data-cities-url");
      var countryId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_city").html(data);
        }
      });

    });
  </script>

{% endblock %}

templates/hr/person_list.html
{% extends 'base.html' %}

{% block title %}Human Resources Module{% endblock %}

{% block content %}
  <h2>Human Resources Module » People Management</h2>

  <p>
    <a href="{% url 'person_add' %}">Add person</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>Country</th>
        <th>City</th>
      </tr>
    </thead>
    <tbody>
      {% for person in people %}
        <tr>
          <td><a href="{% url 'person_change' person.pk %}">{{ person.name }}</a></td>
          <td>{{ person.birthdate }}</td>
          <td>{{ person.country.name }}</td>
          <td>{{ person.city.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'person_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

templates/hr/semester_list_options.html
<option value="">---------</option>
{% for city in semester %}
<option value="{{ city.pk }}">{{ city }}</option>
{% endfor %}

templates/hr/subject_list_options.html
<option value="">---------</option>
{% for s in subject %}
<option value="{{ s.pk }}">{{ s }}</option>
{% endfor %}